"""Regenerates ui_glyphs.inc: every non-ASCII character that appears in showcase.cpp, so the font atlas contains the glyphs the UI text uses
even where they fall outside ImGui's "common Chinese" range (e.g. the characters for "engine" and "button"). Run after changing UI strings:

    python gen_ui_glyphs.py
"""
import os

here = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(here, "showcase.cpp"), encoding="utf-8").read()
chars = sorted({c for c in src if ord(c) >= 0x80})
text = "".join(chars)
with open(os.path.join(here, "ui_glyphs.inc"), "w", encoding="utf-8", newline="\n") as f:
    f.write("// GENERATED by gen_ui_glyphs.py from the strings in showcase.cpp. Do not edit.\n")
    f.write('static const char kUiText[] = "%s";\n' % text)
print(len(chars), "distinct characters")
